server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8087
  servlet:
    context-path: /pofa
    session:
      cookie:
        http-only: true

swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: springfox swagger
  try-host: http://localhost:${server.port}

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher